// Generates lib/pc4-centroids.ts: Dutch PC4 (4-digit postcode) -> [lat, lng] centroid.
// Source: https://github.com/bobdenotter/4pp (CC BY 4.0), derived from CBS/PDOK open data.
// One-off / refreshable: npx tsx scripts/build-pc4.ts
import { writeFileSync } from "node:fs";

const SRC = "https://raw.githubusercontent.com/bobdenotter/4pp/master/4pp.csv";

// Minimal CSV row parser (handles quoted fields containing commas / escaped quotes).
function parseLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (q) {
      if (ch === '"') {
        if (line[i + 1] === '"') (cur += '"'), i++;
        else q = false;
      } else cur += ch;
    } else if (ch === '"') q = true;
    else if (ch === ",") (out.push(cur), (cur = ""));
    else cur += ch;
  }
  out.push(cur);
  return out;
}

async function main() {
  const csv = await (await fetch(SRC)).text();
  const lines = csv.split(/\r?\n/);
  // columns: id,postcode,woonplaats,alt,gemeente,provincie,netnummer,latitude,longitude,soort
  const groups = new Map<string, { good: [number, number][]; any: [number, number][] }>();
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i]) continue;
    const c = parseLine(lines[i]);
    const pc = c[1];
    const lat = parseFloat(c[7]);
    const lng = parseFloat(c[8]);
    const soort = (c[9] || "").trim();
    if (!/^[1-9]\d{3}$/.test(pc) || !isFinite(lat) || !isFinite(lng)) continue;
    if (!groups.has(pc)) groups.set(pc, { good: [], any: [] });
    const g = groups.get(pc)!;
    g.any.push([lat, lng]);
    if (soort !== "Postbus" && soort !== "Onbekend") g.good.push([lat, lng]);
  }
  const out: Record<string, [number, number]> = {};
  for (const pc of [...groups.keys()].sort()) {
    const g = groups.get(pc)!;
    const pts = g.good.length ? g.good : g.any;
    const lat = pts.reduce((s, p) => s + p[0], 0) / pts.length;
    const lng = pts.reduce((s, p) => s + p[1], 0) / pts.length;
    out[pc] = [Math.round(lat * 1e4) / 1e4, Math.round(lng * 1e4) / 1e4];
  }
  const body = Object.entries(out)
    .map(([k, v]) => `"${k}":[${v[0]},${v[1]}]`)
    .join(",");
  const ts =
    `// Auto-generated by scripts/build-pc4.ts — Dutch PC4 -> [lat, lng] centroids.\n` +
    `// Source: bobdenotter/4pp (CC BY 4.0), derived from CBS/PDOK. Do not edit by hand.\n` +
    `export const PC4_CENTROIDS: Record<string, [number, number]> = {${body}};\n`;
  writeFileSync("lib/pc4-centroids.ts", ts);
  console.log(`Wrote ${Object.keys(out).length} PC4 centroids to lib/pc4-centroids.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
